var introduccion = "<font color='#669966'><b>UNISOFT CORPORATED</b></font> es una aplicación web que busca mostrar la interacción entre los miembros de un equipo de desarrollo de software, usando para ello la información obtenida del correo electrónico <a href='https://mail.google.com/' target='_blank'><b>GMAIL</b></a>. Mediante el uso de las herramientas que proporciona la <a href='https://developers.google.com/gmail/api/'' target='_blank'><b>API de GMAIL</b></a> se obtiene la información de cada uno de los miembros del equipo y se muestra de manera gráfica dentro de la aplicación. Esta documentación le guiará a través de la aplicación mostrándole los diversos componentes que la integran y la manera de usarlos.";
/*Componentes*/
var alerta = "En esta sección se muestran los componentes que integran las partes de la interfaz y su funcionamiento. Si desea conocer cada parte de la tabla de contenido por favor continúe en la pestaña <a href='#Home'><b>Home</b></a>.";
var cabecera = "La cabecera principal contiene el logotipo y la barra de navegación. La barra de navegación brinda la posibilidad de traducir las páginas gracias al componente de <b>GOOGLE TRADUCTOR</b>.";
var barra_lateral_izquierda = "La barra lateral izquierda proporciona diferentes opciones que permitirán navegar por los distintos componentes que ofrece la aplicación. Seleccionar una pestaña del menú lo redirige al contenido de la misma, tiene la libertad de navegar por el menú todo lo que desee.";
var barra_lateral_derecha = "La barra lateral derecha es un componente experimental con propósitos por definir. La barra lateral derecha permite mostrar u ocultar contenido de manera fácil y rápida. Pulsando el siguiente botón se puede apreciar el funcionamiento de la barra lateral derecha.";
/*Menú Principal*/
var menu = "El menú principal está compuesto por la parte central de la aplicación. En este se muestra la descripción de la aplicación, los integrantes que la componen, la información gráfica de cada uno y de manera general, un buzón en el que se muestran los correos extraídos y por último la documentación o manual de usuario de la aplicación.";
var principal = "En esta primera pestaña se describe la aplicación y el objetivo que tiene esta. También se presenta la información estadística extraída de manera general de los integrantes del equipo desarrollador, así como también a los integrantes que conforman el equipo de trabajo.";
var integrantes = "En esta pestaña se muestran los integrantes que conforman el equipo de trabajo de manera más detallada, mostrando la información individual extraída de los correos. Al pulsar sobre cada uno de los integrantes se presentan las gráficas que muestran de una mejor manera la información extraída.";
var g_in ="Esta pestaña muestra información individual con respecto a los mensajes enviados y recibidos de un integrante.";
var gen ="Esta pestaña muestra la distribución general de los mensajes enviado con diferentes etiquetas diseñadas para obtener información, de las posibles situaciones que pueden presentarse en el desarrollo de un proyecto. ";
var b_entrada ="En la bandeja de entrada, se pueden ver los mensajes recibidos de los integrantes del grupo con sus respectivas etiquetas.";


/*Descargas*/
var tip = "La plantilla usada fue desarrollada por el equipo <a href='http://almsaeedstudio.com'>Almsaeed Studio</a> y usada como base para poner en marcha la aplicación. Es de código abierto y puede ser descargada en el repositorio de dicho equipo.";
